In [ ]:
import os
import sys
import numpy as np

# garantir acesso ao projeto
sys.path.append(os.path.abspath(".."))
sys.path.append(os.path.abspath("."))

# TF deve ser importado antes do sklearn (conflito de DLL no Windows)
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from scipy.stats import ttest_rel, wilcoxon, friedmanchisquare


In [ ]:
from sklearn.datasets import load_breast_cancer

# Carregar encoder treinado
encoder = tf.keras.models.load_model("../models/encoder.keras")

# Carregar base WDBC
data = load_breast_cancer()
X = data.data
y = data.target

print("Base carregada:", X.shape)
print("Encoder carregado!")

Base carregada: (569, 30)
Encoder carregado!

In [ ]:
def avaliar_repetidamente(modelo, X, y, reps=30, pca=None, ae=None):
    acc_list, prec_list, rec_list, f1_list = [], [], [], []

    for seed in range(reps):
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=seed, stratify=y
        )

        scaler = StandardScaler()
        X_train_s = scaler.fit_transform(X_train)
        X_test_s  = scaler.transform(X_test)

        if pca is not None:
            Z_train = pca.fit_transform(X_train_s)
            Z_test  = pca.transform(X_test_s)
        elif ae is not None:
            Z_train = ae.predict(X_train_s, verbose=0)
            Z_test  = ae.predict(X_test_s, verbose=0)
        else:
            Z_train = X_train_s
            Z_test  = X_test_s

        modelo.fit(Z_train, y_train)
        y_pred = modelo.predict(Z_test)

        acc_list.append(accuracy_score(y_test, y_pred))
        prec_list.append(precision_score(y_test, y_pred, average='weighted', zero_division=0))
        rec_list.append(recall_score(y_test, y_pred, average='weighted', zero_division=0))
        f1_list.append(f1_score(y_test, y_pred, average='weighted', zero_division=0))

    return {
        'acc':  np.array(acc_list),
        'prec': np.array(prec_list),
        'rec':  np.array(rec_list),
        'f1':   np.array(f1_list),
    }


In [3]:
# Criar instâncias dos modelos
rf  = RandomForestClassifier(random_state=42)
svm = SVC(random_state=42)

# PCA fixo com 7 componentes
pca = PCA(n_components=7, random_state=42)

print('Gerando distribuições de acurácia, precisão, recall e F1...')

res_rf_o   = avaliar_repetidamente(rf,  X, y, reps=30)
res_rf_pca = avaliar_repetidamente(rf,  X, y, reps=30, pca=pca)
res_rf_ae  = avaliar_repetidamente(rf,  X, y, reps=30, ae=encoder)

res_svm_o   = avaliar_repetidamente(svm, X, y, reps=30)
res_svm_pca = avaliar_repetidamente(svm, X, y, reps=30, pca=pca)
res_svm_ae  = avaliar_repetidamente(svm, X, y, reps=30, ae=encoder)

# manter compatibilidade com células de testes estatísticos
acc_rf_o   = res_rf_o['acc']
acc_rf_pca = res_rf_pca['acc']
acc_rf_ae  = res_rf_ae['acc']
acc_svm_o   = res_svm_o['acc']
acc_svm_pca = res_svm_pca['acc']
acc_svm_ae  = res_svm_ae['acc']

print('Finalizado!')


Gerando distribuicoes de acuracia, precisao, recall e F1...
Finalizado!


In [ ]:
acc_rf_o[:5], acc_rf_pca[:5], acc_rf_ae[:5]


(array([0.93859649, 0.95614035, 0.98245614, 0.97368421, 0.98245614]),
 array([0.92105263, 0.93859649, 0.96491228, 0.92982456, 0.96491228]),
 array([0.92982456, 0.96491228, 0.96491228, 0.95614035, 0.93859649]))

In [5]:
# Teste t pareado
t_rf_o_pca = ttest_rel(acc_rf_o, acc_rf_pca)
t_rf_o_ae  = ttest_rel(acc_rf_o, acc_rf_ae)
t_svm_o_pca = ttest_rel(acc_svm_o, acc_svm_pca)
t_svm_o_ae  = ttest_rel(acc_svm_o, acc_svm_ae)

# Teste Wilcoxon (não-paramétrico)
w_rf_o_pca = wilcoxon(acc_rf_o, acc_rf_pca)
w_rf_o_ae  = wilcoxon(acc_rf_o, acc_rf_ae)
w_svm_o_pca = wilcoxon(acc_svm_o, acc_svm_pca)
w_svm_o_ae  = wilcoxon(acc_svm_o, acc_svm_ae)

# Friedman (todos os 6 modelos)
friedman = friedmanchisquare(
    acc_rf_o, acc_rf_pca, acc_rf_ae,
    acc_svm_o, acc_svm_pca, acc_svm_ae
)

t_rf_o_pca, w_rf_o_pca, friedman


Friedman: chi2 = 87.0247,  p = 2.83e-17

t-pareado:
  RF_O   vs RF_PCA   t=+2.9588  p=6.0924e-03  **
  RF_O   vs RF_AE    t=+3.9740  p=4.2934e-04  ***
  SVM_O  vs SVM_PCA  t=+4.5452  p=8.9602e-05  ***
  SVM_O  vs SVM_AE   t=+12.5161  p=3.2356e-13  ***

Wilcoxon:
  RF_O   vs RF_PCA   W=  80.5  p=1.5302e-02  *
  RF_O   vs RF_AE    W=  58.0  p=1.5879e-03  **
  SVM_O  vs SVM_PCA  W=  27.0  p=6.8889e-04  ***
  SVM_O  vs SVM_AE   W=   0.0  p=1.8626e-09  ***


In [ ]:
print("RF_O vs RF_PCA:", t_rf_o_pca.pvalue, w_rf_o_pca.pvalue)
print("RF_O vs RF_AE :", t_rf_o_ae.pvalue,  w_rf_o_ae.pvalue)
print("SVM_O vs SVM_PCA:", t_svm_o_pca.pvalue, w_svm_o_pca.pvalue)
print("SVM_O vs SVM_AE :", t_svm_o_ae.pvalue,  w_svm_o_ae.pvalue)


RF_O vs RF_PCA: 0.006092401818108609 0.015301697171108523
RF_O vs RF_AE : 0.00042934140364059065 0.0015879194854225705
SVM_O vs SVM_PCA: 8.9602360522025e-05 0.0006888879718906282
SVM_O vs SVM_AE : 3.235600274498453e-13 1.862645149230957e-09

In [ ]:
import pickle
os.makedirs("../models", exist_ok=True)

resultados = {
    "acc_rf_o": acc_rf_o,
    "acc_rf_pca": acc_rf_pca,
    "acc_rf_ae": acc_rf_ae,
    "acc_svm_o": acc_svm_o,
    "acc_svm_pca": acc_svm_pca,
    "acc_svm_ae": acc_svm_ae,
}

with open("../models/acc_results.pkl", "wb") as f:
    pickle.dump(resultados, f)

print("Distribuições salvas com sucesso!")


Distribuicoes salvas com sucesso!

In [8]:
import pickle
os.makedirs('../models', exist_ok=True)

configs = ['RF_original', 'RF_PCA', 'RF_AE', 'SVM_original', 'SVM_PCA', 'SVM_AE']
resultados_metricas = {
    'RF_original':  res_rf_o,
    'RF_PCA':       res_rf_pca,
    'RF_AE':        res_rf_ae,
    'SVM_original': res_svm_o,
    'SVM_PCA':      res_svm_pca,
    'SVM_AE':       res_svm_ae,
}

with open('../models/metrics_results.pkl', 'wb') as f:
    pickle.dump(resultados_metricas, f)

print('metrics_results.pkl salvo com sucesso!')


metrics_results.pkl salvo com sucesso!


In [9]:
header = f"{'Configuração':<16} {'Acurácia':>22} {'Precisão':>22} {'Recall':>22} {'F1':>22}"
print(header)
print('-' * 96)
for nome, res in resultados_metricas.items():
    acc_m,  acc_s  = res['acc'].mean(),  res['acc'].std()
    prec_m, prec_s = res['prec'].mean(), res['prec'].std()
    rec_m,  rec_s  = res['rec'].mean(),  res['rec'].std()
    f1_m,   f1_s   = res['f1'].mean(),   res['f1'].std()
    row = (f"{nome:<16} "
           f"{acc_m:.4f} ± {acc_s:.4f}   "
           f"{prec_m:.4f} ± {prec_s:.4f}   "
           f"{rec_m:.4f} ± {rec_s:.4f}   "
           f"{f1_m:.4f} ± {f1_s:.4f}")
    print(row)


Configuracao           Acuracia              Precisao                Recall               F1-score
------------------------------------------------------------------------------------------------
RF_original      0.9629 +- 0.0141   0.9632 +- 0.0141   0.9629 +- 0.0141   0.9628 +- 0.0141
RF_PCA           0.9512 +- 0.0197   0.9520 +- 0.0190   0.9512 +- 0.0197   0.9512 +- 0.0196
RF_AE            0.9485 +- 0.0182   0.9491 +- 0.0179   0.9485 +- 0.0182   0.9485 +- 0.0182
SVM_original     0.9760 +- 0.0141   0.9765 +- 0.0137   0.9760 +- 0.0141   0.9760 +- 0.0141
SVM_PCA          0.9670 +- 0.0181   0.9675 +- 0.0176   0.9670 +- 0.0181   0.9669 +- 0.0181
SVM_AE           0.9439 +- 0.0161   0.9447 +- 0.0160   0.9439 +- 0.0161   0.9439 +- 0.0161
